# Generated by Django 6.0.6 on 2026-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_broadcast_event_url_alter_broadcast_vod_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='short_code',
            field=models.CharField(blank=True, help_text="Siglas cortas para la insignia visual de la competición (ej: 'CL', 'NBA', 'F1'). Se usan en vez de logotipos con copyright.", max_length=6),
        ),
    ]
